# config.yaml
# ────────────────────────────────────────────────
# Canonical Configuration for MLB Prediction Pipeline
# Supports modules A–L, CLI overrides, overwrite policy
# ────────────────────────────────────────────────

logs:
  pipeline_log: logs/pipeline.log

pipeline:
  concurrency: 2
  continue_on_failure: true

overwrite_policy: warn

inputs:
  seasons: [2022, 2023]
  recent_gamelogs_csv: outputs/gamelogs/recent_gamelogs.csv
  static_player_csv: outputs/static/static_player_metadata.csv
  static_team_csv: outputs/static/static_team_metadata.csv
  true_lines_dir: outputs/true_lines
  recent_predictions_dir: outputs/predictions/recent
  combined_preds_dir: outputs/predictions/combined
  gamelogs_source: statsapi
  context_features: ""
  static_csvs:
    - name: teams
      url: https://example.com/teams.csv
    - name: stadiums
      url: https://example.com/stadiums.csv

outputs:
  gamelogs_dir: outputs/gamelogs/
  static_dir: outputs/static/
  context_dir: outputs/context/
  merged_dir: outputs/merged/
  starters_dir: outputs/starters/
  full_feature_set: outputs/features/full_feature_set.parquet
  consolidated_predictions: outputs/predictions/consolidated_predictions.parquet
  model_dir: outputs/models/
  model_predictions: outputs/predictions/final.parquet
  root: outputs
  logs_dir: logs/

rolling_windows:
  windows:
    - days: 7
      stats: ["hits", "HR", "RBI", "SB"]
    - days: 30
      stats: ["hits", "HR", "RBI", "SB", "BB", "K"]

model:
  model_type: xgboost
  params:
    max_depth: 6
    n_estimators: 100
    learning_rate: 0.1
  random_state: 42

cli:
  overwrite_policy: safe  # options: safe, force, skip
  log_level: INFO

logging:
  max_bytes: 5000000
  backup_count: 3
  level: INFO

flags:
  use_cached_data: true
  save_predictions: true

required_features: []
paths: {}
